insert into productos(nombre, precio, create_at) values ('Panasonic', 1000, now());
insert into productos(nombre, precio, create_at) values ('Sony', 500, now());
insert into productos(nombre, precio, create_at) values ('Apple', 2000, now());
insert into productos(nombre, precio, create_at) values ('Lenovo', 1500, now());
insert into productos(nombre, precio, create_at) values ('HP', 200, now());
insert into productos(nombre, precio, create_at) values ('AMD', 2500, now());
insert into productos(nombre, precio, create_at) values ('Intel', 1800, now());
insert into productos(nombre, precio, create_at) values ('Amazon', 700, now());
insert into productos(nombre, precio, create_at) values ('Hitachi', 450, now());